# Execute your favorite apps at launch
#exec-once = waybar
exec-once = awww-daemon
#exec-once = dunst
#exec-once = swaync
exec-once = noctalia-shell
exec-once = hyprctl setcursor Catppuccin-Mocha-Light-Cursors 24
exec-once = hypridle
